### ISSUE TITLE
老是返回 invalid_credentials

### ISSUE THREAD

**Issue by awesomes-cn** [beenhero/omniauth-weibo-oauth2#14]
我的key和sercrete 都没错，为什么老是在授权后就跑到 /auth/failure?message=invalid_credentials&origin=http%3A%2F%2Fwww.awesomes.cn%2F&strategy=weibo 这呢

我的环境是

ruby 2.2.1
rails 4.2.4

**Comment by imvic999** [comment]
I have the same issue, still figure it out

**Comment by xfstart07** [comment]
@awesomes-cn https://github.com/beenhero/omniauth-weibo-oauth2/pull/15 可以看一下这个 PR，重写了 access_token 的获取方式

**Comment by awesomes-cn** [comment]
@xfstart07 谢谢，作者好像不再维护这个包了

**Comment by beenhero** [comment]
感谢 @xfstart07 的 #15 
已经 merge，并发布了新的版本到 rubygems.

**Comment by wayne712** [comment]
Hi all, I still get the same problem,  need help
