### ISSUE TITLE
多个改动导致在默认配置下不可用

### ISSUE THREAD

**Issue by acenqiu** [beenhero/omniauth-weibo-oauth2#21]
## image_size

配置支持设置image_size，但是没有设置默认值，导致`options[:image_size].to_sym`报错。修改如下：

``` ruby
option :image_size, :middle
```
## redirect_uri

配置支持设置`redirect_uri`，但是没有设置默认值，导致没有设置时，`get_token`请求不含`redirect_uri`参数，进而导致产生`invalid_credential`的错误。建议回退[rewrite build_access_token method](https://github.com/beenhero/omniauth-weibo-oauth2/commit/02899bd1d4ada2640c19daee2797d22ebc1d6a00)。从源码看，`omniauth`本身是支持配置的，所以重写`build_access_token`方法没必要，没实际测试。

**Comment by fantasticfears** [comment]
快一年没更新了。 @beenhero 你有合适的人能和你一起管理这个 gem 么？

**Comment by NeverMin** [comment]
Hi @acenqiu , 关于 redirect_uri 问题, @beenhero 已合并了 PR #24 , 如果你还有环境的话, 请再确认. 至于 image_size 我在 omniauth 1.6.1 版本下正常.
