### ISSUE TITLE
新浪用账号登录没问题，扫码异常

### ISSUE THREAD

**Issue by lazyb0ne** [beenhero/omniauth-weibo-oauth2#31]
https://segmentfault.com/q/1010000006976187/a-1020000006985587
“手工输入新浪的账号密码，可以跳到我的回调页获取token，新浪用户信息。
但是用他们的二维码扫码登录，token就获取不到了。”

我也遇到了，请问是什么原因。用账号密码登录没问题，扫码登录偶尔会callback和failure同时被回调。

**Comment by NeverMin** [comment]
我试了一下，确实如此，但是我后退回来发现已经完成了授权，我要再进一步测试。

感谢你的反馈。

-Never

**Comment by lazyb0ne** [comment]
有没有什么思路？指点下我也调试下

**Comment by NeverMin** [comment]
就微信(为此我特别看了京东上,人家移动版本根本没有微信登录)的接口看来, 有可能是两个 API. 如果是我来分析的话, 我会抓包分析,
对比输入密码的方式和扫码的方式有何不同. 你也可以试试看.

**Comment by NeverMin** [comment]
@lazyb0ne 造成扫码不可用的原因是新浪方面使用了不同于密码登录的认证接口, 在扫码的时候实际上是重新请求了另外一个认证接口但使用了同一个 `state`, 触发了 `CSRF detected`. 

我暂时没想到好的解决办法, 暂时来说, 可能是二挑一, 即固定你的应用是扫码登录, 或是输入密码登录, 新浪没有关于二维码的认证说明(或是我没有找到.).

期待想到更好的解决办法.

**Comment by NeverMin** [comment]
fixed 0.5.0, ready to release.

**Comment by NeverMin** [comment]
fixed in 0.5.0, ready to release. can you help me test first?

**Comment by NeverMin** [comment]
done. push to rubygems.org
