### ISSUE TITLE
request.env['omniauth.origin'] 返回nil

### ISSUE THREAD

**Issue by HanTsing** [beenhero/omniauth-weibo-oauth2#6]

**Comment by ryancheung** [comment]
The same is in Rails 5

**Comment by NeverMin** [comment]
Rails 5.1.4 + omniauth 1.6.1 worked fine, I just close now, if you have any issue, reopen please and tell me more.

Thanks for feedback! :heart:

**Comment by ryancheung** [comment]
I found a workaround: 
`/users/auth/wechat?origin=your_redirect_url_after_auth`

**Comment by NeverMin** [comment]
Hi @ryancheung , thank you for information, maybe PR #24 for you, right? welcome feedback.

> /users/auth/wechat?origin=your_redirect_url_after_auth

no wechat:
`/users/auth/weibo?origin=your_redirect_url_after_auth`
